version: '3.8'

services:
  frontend:
    build:
      context: ./app/frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./app/backend/core
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - mongodb

  postgres:
    build:
      context: ./db/postgresql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  mongodb:
    build:
      context: ./db/mongodb
    ports:
      - "27017:27017"

networks:
  default:
    external:
      name: mynetwork
