version: '3.8'

services:
  frontend:
    build:
      context: ./app/frontend
    ports:
      - "80:80"
    volumes:
      - ./app/frontend:/app/frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./app/backend/core
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - mongodb
    volumes:
      - ./app/backend/core:/app/backend/core

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./db/.data/postgresql:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db/.data/mongodb:/data/db

networks:
  default:
    external:
      name: mynetwork
